-- Create cities
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(1,'HUELVA');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(2,'CADIZ');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(3,'SEVILLA');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(4,'MALAGA');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(5,'CORDOBA');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(6,'JAEN');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(7,'GRANADA');
INSERT INTO CITY(CITY_ID,CITY_NAME) VALUES(8,'ALMERIA');


-- Create connections between cities

-- Huelva and Cadiz (1.5h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(1, 1, 2, PARSEDATETIME('00:00', 'HH:mm'), PARSEDATETIME('01:30', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(2, 2, 1, PARSEDATETIME('00:00', 'HH:mm'), PARSEDATETIME('01:30', 'HH:mm'));

-- Huelva and Sevilla (1h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(3, 1, 3, PARSEDATETIME('12:00', 'HH:mm'), PARSEDATETIME('13:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(4, 3, 1, PARSEDATETIME('12:00', 'HH:mm'), PARSEDATETIME('13:00', 'HH:mm'));

-- Sevilla and Cadiz (0.75h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(5, 3, 2, PARSEDATETIME('13:45', 'HH:mm'), PARSEDATETIME('14:30', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(6, 2, 3, PARSEDATETIME('13:45', 'HH:mm'), PARSEDATETIME('14:30', 'HH:mm'));

-- Sevilla and Cordoba (1.5h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(7, 3, 5, PARSEDATETIME('10:00', 'HH:mm'), PARSEDATETIME('11:30', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(8, 5, 3, PARSEDATETIME('10:00', 'HH:mm'), PARSEDATETIME('11:30', 'HH:mm'));

-- Cadiz and Malaga (8h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(9, 2, 4, PARSEDATETIME('14:00', 'HH:mm'), PARSEDATETIME('22:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(10, 4, 2, PARSEDATETIME('14:00', 'HH:mm'), PARSEDATETIME('22:00', 'HH:mm'));

-- Malaga and Cordoba (2h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(11, 4, 5, PARSEDATETIME('08:00', 'HH:mm'), PARSEDATETIME('10:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(12, 5, 4, PARSEDATETIME('08:00', 'HH:mm'), PARSEDATETIME('10:00', 'HH:mm'));

-- Malaga and Granada (4h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(13, 4, 7, PARSEDATETIME('09:00', 'HH:mm'), PARSEDATETIME('13:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(14, 7, 4, PARSEDATETIME('09:00', 'HH:mm'), PARSEDATETIME('13:00', 'HH:mm'));

-- Cordoba and Jaen (3h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(15, 5, 6, PARSEDATETIME('05:00', 'HH:mm'), PARSEDATETIME('08:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(16, 6, 5, PARSEDATETIME('05:00', 'HH:mm'), PARSEDATETIME('08:00', 'HH:mm'));

-- Jaen and Granada (5h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(17, 6, 7, PARSEDATETIME('15:00', 'HH:mm'), PARSEDATETIME('20:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(18, 7, 6, PARSEDATETIME('15:00', 'HH:mm'), PARSEDATETIME('20:00', 'HH:mm'));

-- Jaen and Almeria (6h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(19, 6, 8, PARSEDATETIME('17:00', 'HH:mm'), PARSEDATETIME('23:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(20, 8, 6, PARSEDATETIME('17:00', 'HH:mm'), PARSEDATETIME('23:00', 'HH:mm'));

-- Granada and Almeria (2h)
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(21, 7, 8, PARSEDATETIME('19:00', 'HH:mm'), PARSEDATETIME('21:00', 'HH:mm'));
INSERT INTO CITY_CONNECTION(CITY_CONNECTION_ID, CITY_ID_ORIGIN, CITY_ID_TARGET, DEPARTURE_TIME, ARRIVAL_TIME)
VALUES(22, 8, 7, PARSEDATETIME('19:00', 'HH:mm'), PARSEDATETIME('21:00', 'HH:mm'));

COMMIT;